### ISSUE TITLE
ERROR: dependency ‘SSOAP’ is not available for package ‘xMSannotator’

### ISSUE THREAD

**Issue by amaurypm** [yufree/xMSannotator#2]
Hello,
The package is no longer installable, as SSOAP is a dependency and it was removed from CRAN. The legacy SSOAP package can not be installed, as it depends on XMLSchema, which is also no longer available.

**Comment by yufree** [comment]
Two options:

1. install the package from github repo:

`devtools::install_github('omegahat/XMLSchema');devtools::install_github('cran/SSOAP')`

2. use this docker [image](https://hub.docker.com/r/yufree/xcmsrocker/) to get common packages for metabolomics. I will maintain this image to make sure all the package could be available.

**Comment by amaurypm** [comment]
Great, it worked!
Thank you very much.
It would be nice that the installation instruction to be updated, but I guess this issue report could be useful for others having the same problem.

**Comment by yufree** [comment]
I just updated the `readme`. 

Since I am not the maintainer of this package(I am a user), I strongly recommend contacting Dr. Karan Uppal(kuppal2 at emory.edu) for the further technique issue.  

Well, this id might be him @kuppal2 ...
