### ISSUE TITLE
Package installation failure

### ISSUE THREAD

**Issue by rpollak** [yufree/xMSannotator#5]
I used the installation instructions in the ReadMe file (as updated after the error opened by @amaurypm on Oct 10), and installation is still failing. These are the error messages I got:
Error : object ‘enexprs’ is not exported by 'namespace:rlang'
Error : package ‘WGCNA’ could not be loaded
ERROR: lazy loading failed for package ‘xMSannotator’

Not sure if the install instructions need to be updated - help?

**Comment by yufree** [comment]
Hi, that error means you need to install `rlang` package. Could you try the following code:

```
install.packages('rlang')
```
It seems this issue is caused by the dependent issue. I will look into it after the holiday if that command does not help.

**Comment by rpollak** [comment]
I think the issue is that I'm using R version 3.3.3 - is there a version you recommend using for xMSannotator?

**Comment by yufree** [comment]
I am using 3.5.1 and it works well. I could not reproduce that error and I suggested you update your R(some packages might require a certain version of R and be careful).

**Comment by rpollak** [comment]
Updated R and everything is working fine now. Thank you!
